version: '2'
services:
  db:
    image: mongo:latest
  api:
    build: .
    image: mern-dashboard
    command: npm start
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  web:
    image: mern-dashboard
    command: npm start --prefix client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/src/app/client
      - /usr/src/app/client/node_modules
    depends_on:
      - api
