export const GET_ERRORS = "GET_ERRORS";
export const ADMIN_LOADING = "ADMIN_LOADING";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const SET_CURRENT_REVIEWER = "SET_CURRENT_REVIEWER";
export const REVIEWER_LOADING = "REVIEWER_LOADING"
