export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_ADMIN = "SET_CURRENT_ADMIN";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER_DATA = "SET_USER_DATA";
export const SET_PRODUCT_DATA = "SET_PRODUCT_DATA";